### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by highsource** [derhuerst/hafas-client#1]
Could you please include the license?

**Comment by derhuerst** [comment]
Both [the license file](https://github.com/derhuerst/hafas-client/blob/df39896/license.md) as well as [the `license` field](https://github.com/derhuerst/hafas-client/blob/efe2111/package.json#L11) indicate that this project is ISC-licensed.

**Comment by highsource** [comment]
Sorry, I've missed license.md somehow.

**Comment by derhuerst** [comment]
I'm curious: What are you planning to build using `hafas-client`?

**Comment by highsource** [comment]
Like bahnhof.direct but for RMV and other companies using HAFAS. They normally have a departure board, I just have to locate the nearest stop. I want this to work cross-provider.

**Comment by derhuerst** [comment]
Together with @juliuste i did roughly the following, both for VBB & DB:

- download the iOS app, open once & fully close again
- setup [mitmproxy](https://mitmproxy.org) on your computer & the iOS device
- sniff traffic when check departures, e.g. like [this](https://gist.github.com/derhuerst/2a735268bd82a0a6779633f15dceba33#file-station-board-http)
- write a wrapper `foo-hafas` around [`hafas-client`](https://github.com/derhuerst/hafas-client)

**Comment by highsource** [comment]
Do I need a jailbroken iOS device?

**Comment by juliuste** [comment]
> Do I need a jailbroken iOS device?

No 👍

**Comment by derhuerst** [comment]
[Ping us on Gitter](https://gitter.im/derhuerst/vbb-rest) or in the OKDE Slack channel if you need assistance or want to chat about more public transport things.

**Comment by highsource** [comment]
I'me MITMed the RMV app and found out that it's not using "standard" HAFAS endpoints so using `hafas-client` with it would not quite work out. However I've found a suitable endpoint to quickly grab stops:

https://www.rmv.de/auskunft/bin/jp/query.exe/3deuny?performLocating=2&tpl=stop2json&look_stopclass=2147483647&look_maxx=9000000&look_maxy=55000000&look_minx=8000000&look_miny=40000000

**Comment by highsource** [comment]
https://github.com/highsource/rmv-stops

**Comment by derhuerst** [comment]
> I'me MITMed the RMV app and found out that it's not using "standard" HAFAS endpoints

Which does it use? For the sake of not redoing work all the time, would you mind publishing the recorded HTTP requests somewhere, e.g. in a gist? 

`hafas-client` talks to `mgate.exe` which is indeed not the endpoint the docs mention of the website uses, but it is what VBB & DB apps call.

**Comment by derhuerst** [comment]
> https://www.rmv.de/auskunft/bin/jp/query.exe/3deuny?performLocating=2&tpl=stop2json&look_stopclass=2147483647&look_maxx=9000000&look_maxy=55000000&look_minx=8000000&look_miny=40000000

That looks like manually generated JSON. I don't really wanna know what other scary things happen inside the code. :grin:

**Comment by highsource** [comment]
Definitely not manually generated. :) I got ca. 17000 stops at the end.

**Comment by derhuerst** [comment]
FYI:

I have almost finished reworking `hafas-client` in the `any-endpoint` branch. **Instead of being a utility repo for the `*-hafas` repos, it now contains all the logic necessary to fetch data.** `*-hafas` will become merely thin wrappers to reduce boilerplate code for users. The [endpoint-specific customisations (called "profiles") in `p`](https://github.com/derhuerst/hafas-client/tree/any-endpoint/p) contain e.g. the URL to fetch from.

With this architecture, it should become a lot easier to adapt `hafas-client` to any HAFAS endpoint. In fact, once i'm done with this, I will try to write a profile for ÖBB.

**Comment by amirhouieh** [comment]
Any update on `*-hafas`? 
@highsource RMV has a an [API ^_^ ](https://www.rmv.de/hapi) which I think would work for what you need.

**Comment by derhuerst** [comment]
@amirhouieh [We've worked on `hafas-client` quite a bit](https://github.com/derhuerst/hafas-client/commits/master?after=7ce65ca480c9f199f80065e20833ea502ee89f4b+0), it now supports ÖBB (Austrian Railways) and soon NASA/INSA (Sachsen-Anhalt). I'm about to create a thin wrapper `oebb-hafas` around the ÖBB profile.

I haven't looked into RMV yet, though.

**Comment by juliuste** [comment]
@derhuerst [`oebb-hafas`](juliuste/oebb-hafas) already exists 😄

**Comment by amirhouieh** [comment]
@derhuerst cool. Unfortunately I need to only work with RMV, but Frankfurt area is like a black whole👎 , there is nothing! I have access to their API and still some endpoints are missing. 
I would like to make `rmv-hafas`, but no idea how and where to start. Is there any document/guide about implementing profile?

**Comment by derhuerst** [comment]
@amirhouieh [`jfilter` and I recently implemented INSA](), and during this process, I learned about a few remaining berries, e.g. non-obvious relationships between things.

I will write a guide soon, and let you know so you can try with RMV.

**Comment by derhuerst** [comment]
@highsource I'm planning to write a client for the [open XML-based RMV API](https://www.rmv.de/hapi/) that you mentioned 2 years ago. Are you aware of any open clients for it?

Also, is there another RMV API in another format? For example, I couldn't find any `mgate.exe`-based one.

**Comment by highsource** [comment]
@derhuerst I'm sorry I really don't know much about RMV.

**Comment by highsource** [comment]
@derhuerst I don't even remember mentioning that API. :(

**Comment by schildbach** [comment]
rmv.de is data-identical to nvv.de. So there is no need to implement RMV separately.

**Comment by derhuerst** [comment]
For what it's worth, RMV seems to have an `mgate.exe` endpoint (now?): https://github.com/marudor/BahnhofsAbfahrten/blob/cb642d94f6ccea42822f66adfc49869c488d1865/src/server/HAFAS/profiles.ts#L96-L113
