### ISSUE TITLE
not getting a journey when using `via` parameter in `vbb-rest`

### ISSUE THREAD

**Issue by pepebecker** [derhuerst/hafas-client#12]
## Request

[`GET https://vbb.transport.rest/journeys?from=900000013102&to=900000009202&via=900000009102`](https://vbb.transport.rest/journeys?from=900000013102&to=900000009202&via=900000009102)

## Result

```json
{
  "error": true,
  "msg": "VBB error: HCI Service: location missing or invalid"
}
```

## Passed Parameters

Key | Station ID | Station Name
---- | ---------- | -------------
from | 900000013102 | Kottbusser Tor
to | 900000009202 | Osloer Straße
via | 900000009102 | Leopoldplatz

## Expected Result

A Journey from `Kottbusser Tor` over `Leopoldplatz` to `Osloer Straße`

**Example**: `Kottbusser Tor` -> `Hallesches Tor` -> `Leopoldplatz` -> `Osloer Straße`

**Comment by derhuerst** [comment]
Fixed in derhuerst/hafas-client@20a2c8de94ae0fcc0a7712517e124d720c037596 for `2.vbb.transport.rest` and `1.db.transport.rest`.

Fixed in derhuerst/vbb-hafas@ed167afbf15dd2809cfd1747ff45bc8658786649 for `vbb.transport.rest`.

@pepebecker Can you confirm that it works?

**Comment by derhuerst** [comment]
Apparently the newly added tests in `hafas-client` are unreliable. https://travis-ci.org/derhuerst/hafas-client/builds/331182566

**Comment by derhuerst** [comment]
@pepebecker Can you confirm that it works?

**Comment by pepebecker** [comment]
@derhuerst Yes it works, awesome!
