### ISSUE TITLE
Information: Meaning of d.stbStop.dTimeR

### ISSUE THREAD

**Issue by Bertware** [derhuerst/hafas-client#2]
I found the following TODO: https://github.com/derhuerst/hafas-client/blob/d72fdc80921ad3d1ec494d676fbbb2c0d879d47d/parse.js#L144

Not sure if this is still an issue, but anyway, here is a list of fields I've identified in a stationBoard response, journey responses are similar

Here is an example journeyList from a stationboard with clarifications, from what I learned:
```
{
      "jid": "1|593|7|80|9112017", < Journey Id, used to retrieve details from vehicle page >
      "date": "20171109", < Date of departure >
      "prodX": 0, < Line/Service number > 
      "dirTxt": "Ronse / Renaix", < Headsign of the vehicle / direction text >
      "status": "P", < Unknown, always P for stationboards. Maybe for PROGNOSED? >
      "isRchbl": true, < Unknown, always true for nmbs > 
      "isPartCncl": true, < Partially canceled train, means some stops ahead or earlier are canceled >
      "isCncl": true, < Completely canceled train, doesn't appear together with isPartCncl >
      "stbStop": {
          "locX": 0, < Location of this stop > 
          "idx": 7, < Id of this object? >
          "dCncl": true < Departure is canceled >
          "dProdX": 0, < Departure Line/Service number > 
          "dPlatfS": "4", < Scheduled departure platform>
          "dPlatfR": "3", < Realtime departure platform in case of platform change>
          "dTimeS": "160000", <Scheduled departure time>
          "dTimeR": "160000", < Realtime departure date>
          "dProgType": "PROGNOSED" <Departure prognose type>
       }
}
```
I came across following ProgType values: Scheduled, Reported, Prognosed, Calculated, Corrected, Partial_Failure_at_arr, Partial_failure_at_dep, canceled.
Partial failure indicates that the arrival or departure is canceled. Reported means the train left or arrived. This doesn't seem to be reliable on all endpoints however.

All values starting with lowercase d affect departures, all values starting with a affect arrivals. It seems they keep compatibility between the journey and stationboard data by using the same formats, which explains why they explicitly define the information as departure information.

R always indicates Realtime data (changes from the original plan), while S indicates a schedule. L at the end always indicates a List.

Our (iRail) implementation of Hafas parsing, in case it helps:
https://github.com/iRail/iRail/blob/master/api/data/NMBS/connections.php

You might know most (or all) of this information already, but I hope it can be a help. Feel free to ask if there are other fields you haven't figured out yet!

**Comment by derhuerst** [comment]
Thanks for this! :green_heart: Indeed, I know most of this. The TODO about `what is d.stbStop.dTimeR` therefore was a leftover, sorry for that.

I didn't know all the `ProgType` values you mentioned:

- `Scheduled`
- `Reported`
- `Prognosed`
- `Calculated`
- `Corrected`
- `Partial_Failure_at_arr`
- `Partial_failure_at_dep`
- `canceled`

Are these all? Is `canceled` really lowercased?

> This doesn't seem to be reliable on all endpoints however.

Seems like it, as I haven't seen most of them in the VBB & DB endpoints yet. But maybe I didn't pay enough attention.

> Our (iRail) implementation of Hafas parsing, in case it helps:
> https://github.com/iRail/iRail/blob/master/api/data/NMBS/connections.php

Thanks. I guess this will mostly help others who want to query HAFAS endpoints. We should really make a documentation/FAQ/help repo in @public-transport to help future fellow programmers. @juliuste are you in on this?

BTW great job with iRail! I think [my VBB API](https://github.com/derhuerst/vbb-rest/tree/master/docs) could eventually become something similar, given that VBB gives permission to me.

**Comment by Bertware** [comment]
`Are these all? Is canceled really lowercased?` I did a quick write-up on all types I've seen up till now, they're all in all-caps in API responses.

I noted that on route requests the progtype changes, but on stationboard it doesn't changed at all, it's weird. I'm mostly looking for ways to detect if a train left/arrived when viewing all departures for a station. While checking those progtypes works for routes, there doesn't seem to be any field with this information for stations. Even the official app doesn't show it. Actually, do you happen to know any Hafas-based app that shows a list of departures for a station, including if the train arrived/left?

I'm still trying to find out what isRchbl and Status are, but no luck so far. 

Thanks for the compliment! Having some Hafas documentation would be nice, just query parameters and the meaning of fields would be nice. Which fields are returned might not be 100% consistent over multiple transport providers, but as long as the naming is consistent, it'd help a lot with decoding API responses.

I've actually been wondering if it would be possible to create something iRail-like, but generic for any Hafas Mobile API. There seem to be a lot of transport providers using Hafas, so it'd have the potential of being re-usable throughout Europe.

**Comment by derhuerst** [comment]
> Which fields are returned might not be 100% consistent over multiple transport providers, but as long as the naming is consistent, it'd help a lot with decoding API responses.

My personal take on on this was `hafas-client`. In the beginning, I wrote `vbb-hafas`, but as soon as I had started working on `db-hafas`, I knew it would make sense to move shared logic into a module called `hafas-client`. It's not generalised enough to server all HAFAS endpoints though.

> I've actually been wondering if it would be possible to create something iRail-like, but generic for any Hafas Mobile API. There seem to be a lot of transport providers using Hafas, so it'd have the potential of being re-usable throughout Europe.

With an even more ambitious perspective, @juliuste and I created the [*Friendly Public Transport Format* (FPTF)](https://github.com/public-transport/friendly-public-transport-format#friendly-public-transport-format-fptf), which intends to work in both static data and API calls. [We're just working on bringing the first fixed version out.](https://github.com/public-transport/friendly-public-transport-format/issues/10) There's also [a list of modules working with FPTF](https://github.com/public-transport/friendly-public-transport-format/blob/master/modules.md#fptf-javascript-modules).

Also, @juliuste compiled [a list of European transport providers](https://github.com/public-transport/european-transport-operators#european-transport-operators). He's working on putting green check marks into that table. 😄

**Comment by derhuerst** [comment]
>> Are these all? Is canceled really lowercased?

> I did a quick write-up on all types I've seen up till now [...].

Okay, thanks.

> [...] they're all in all-caps in API responses.

Yes, I forgot.

> I'm still trying to find out what isRchbl and Status are, but no luck so far.

I guess you've guessed that as well by now, but `isRchbl` really looks a lot like `isReachable`.

**Comment by derhuerst** [comment]
I will close this for now, as the TODO was a leftover, but thanks for you input!
