### ISSUE TITLE
refactor products/modes markup

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/hafas-client#29]
The current markup is a mess, spread over [two](https://github.com/derhuerst/hafas-client/blob/828ef4ad47df31f303ad898d376717252126e076/p/db/modes.js) [places](https://github.com/derhuerst/hafas-client/blob/828ef4ad47df31f303ad898d376717252126e076/p/db/index.js#L106-L117) and with lots of explicitly or implicitly redundant values.

Let's make a new one. It might look like this:

```
// products.js
module.exports = [
  {
    id: 'subway',
    mode: 'train',
    name: 'U-Bahn',
    short: 'U',
    bitmasks: [64, 128], // some endpoints assign several digits to one product
    default: true
  }
  // ...
]
```

**Comment by derhuerst** [comment]
This would be a breaking change because you use `hafas-client` with other profiles than the bundled ones.

**Comment by derhuerst** [comment]
The `unknown` product should also be moved from the markup into the parsing code.

**Comment by juliuste** [comment]
By the way, we should agree on what the `name` key should represent. There's always the "original" names (mostly german), e.g. "Durchgangszug", which often don't have an accurate translation in English.

**Comment by derhuerst** [comment]
Looking at it theoretically, I think it would be good to have multiple names (at least the local one and English) for a product. But maybe this would be a bit over the top.

In the ["Writing a profile" guide](https://github.com/derhuerst/hafas-client/blob/9b6c07e477f736660c7f7cc53a59e869220eb551/docs/writing-a-profile.md#3-products), I've used the following phrase:

> A short, but distinct name for the means of transport, just precise enough in local context. In Berlin, S-Bahn commuter rail would be too much, because everyone knows what S-Bahn means.

Maybe we should add that it is about the name in the local language/context.
