### ISSUE TITLE
The requestes 3 examples for INSA

### ISSUE THREAD

**Issue by jfilter** [derhuerst/hafas-client#31]
**1. Requires at least changing once**

Magdeburg, Hasselbachplatz (Sternstr.) (Tram/Bus) to Stendal via Dessau 

**2. No changing required**

Magdeburg, Hasselbachplatz (Sternstr.) (Tram/Bus) to Magdeburg, Universität via Magdeburg, Breiter Weg

**3. the same as 2.?**

**Comment by derhuerst** [comment]
This is the INSA part of #26.
